{{- if eq .Values.controllerManagerConfig.clusterDopplersecretNamespace "doppler-operator-system" }}
apiVersion: v1
kind: Namespace
metadata:
  name: doppler-operator-system
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
