apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-manager-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: {{ .Values.managerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}