---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.doppler.com
  resources:
  - dopplersecrets/status
  verbs:
  - get
  - patch
  - update
