{{- if .Values.csiProvider.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "doppler-operator.fullname" . }}-csi-provider
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "doppler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: csi-provider
{{- end }}
