apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doppler-operator.fullname" . }}-controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "doppler-operator.labels" . | nindent 4 }}
    {{- include "doppler-operator.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "doppler-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "doppler-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "doppler-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--health-probe-bind-address=:8081"
            - "--metrics-bind-address=127.0.0.1:8080"
            {{- if .Values.leaderElect }}
            - "--leader-elect"
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - NET_RAW
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
