apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "doppler-operator.labels" . | nindent 4 }}
    {{- include "doppler-operator.selectorLabels" . | nindent 4 }}
