name: Scanners

permissions:
  contents: read

on:
  pull_request:

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770
        with:
          args: ./...

  govulncheck:
    runs-on: ubuntu-latest
    name: govulncheck
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - id: govulncheck
        uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd
        with:
          repo-checkout: false
          cache-dependency-path: "go.sum"
          go-package: ./...
